<?php

return array (
  'BOT_TOKEN' => NULL,
  'CORS_ALLOW_ORIGIN' => NULL,
  'DATABASE_URL' => NULL,
  'JWT_PASSPHRASE' => NULL,
  'JWT_PUBLIC_KEY' => NULL,
  'JWT_SECRET_KEY' => NULL,
  'JWT_TOKEN_TTL' => NULL,
  'MAILER_URL' => NULL,
);
