nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
#        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
#        allow_headers: ['Content-Type', 'Authorization']
        allow_headers: ['*']
        expose_headers: ['Link']
        max_age: 3600
        forced_allow_origin_value: '*'
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['*']
#            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            #        allow_headers: ['Content-Type', 'Authorization']
            allow_headers: ['*']
            expose_headers: ['Link']
            max_age: 3600
            forced_allow_origin_value: '*'
