version: "3.6"

services:
    php:
        container_name: "php-${PROJECT_NAME}"
        build:
            args:
                - KEY=${GITH_KEY}
            context: .
            dockerfile: .docker/php-fpm/Dockerfile
        depends_on:
            - nginx
        networks:
            - backend-flags
    nginx:
        container_name: "nginx-${PROJECT_NAME}"
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        restart: always
        networks:
            - backend-flags
    db:
        build:
            context: .
            dockerfile: .docker/mysql/Dockerfile
        container_name: "db-${PROJECT_NAME}"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - db-data-flags:/var/lib/mysql
        restart: always
        networks:
            - backend-flags
networks:
    backend-flags:
volumes:
    db-data-flags: ~
