version: "3.6"
services:
    php:
        environment:
            VERSION_HASH: "${GITHUB_SHA:-none}"
            SYMFONY_DECRYPTION_SECRET: "${SYMFONY_DECRYPTION_SECRET}"
        extends:
            file: docker-compose.yml
            service: php
#        image: ${IMAGE}:php-staging
        build:
            dockerfile: .docker/php-fpm/Dockerfile
        networks:
            - backend-flags-staging
    nginx:
        extends:
            file: docker-compose.yml
            service: nginx
        image: ${IMAGE}:nginx-latest
        container_name: "nginx-${PROJECT_NAME}"
        ports:
            - "8080:80"
            - "4443:443"
        networks:
            - backend-flags-staging
    db:
        extends:
            file: docker-compose.yml
            service: db
        image: ${IMAGE}:db-latest
        environment:
            MYSQL_DATABASE: "flags_staging"
        ports:
            - "33061:3306"
        networks:
            - backend-flags-staging
networks:
    backend-flags-staging:
        external: true
volumes:
    db-data-flags-staging: ~
