version: "3.6"
services:
    php:
        container_name: "php-staging-${PROJECT_NAME}"
        build:
            args:
                KEY: ${GITH_KEY}
            context: .
            dockerfile: .docker/php-fpm/Dockerfile
        depends_on:
            - nginx
        environment:
            VERSION_HASH: "${GITHUB_SHA:-none}"
            SYMFONY_DECRYPTION_SECRET: "${SYMFONY_DECRYPTION_SECRET}"
        networks:
            - backend-flags-staging
    nginx:
        container_name: "nginx-staging-${PROJECT_NAME}"
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        restart: always
        ports:
            - "8080:80"
            - "4443:443"
        networks:
            - backend-flags-staging
    db:
        build:
            context: .
            dockerfile: .docker/mysql/Dockerfile
        container_name: "db-staging-${PROJECT_NAME}"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "flags_staging"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - db-data-flags-staging:/var/lib/mysql
        restart: always
        ports:
            - "33061:3306"
        networks:
            - backend-flags-staging
networks:
    backend-flags-staging:
        external: true
volumes:
    db-data-flags-staging: ~
